apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 32.4.3
    helm:
      releaseName: portfolio-kafka
      values: |
        global:
          security:
            allowInsecureImages: true
        image:
          registry: docker.io
          repository: bitnami/kafka
          tag: latest
        kraft:
          enabled: true
        listeners:
          client:
            protocol: SASL_PLAINTEXT
          controller:
            protocol: SASL_PLAINTEXT
          interbroker:
            protocol: SASL_PLAINTEXT
          external:
            protocol: SASL_PLAINTEXT
        sasl:
          client:
            users:
              - kyhan
            passwords: ""
          interbroker:
            users:
              - admin
            passwords: ""
          controller:
            users:
              - controller
            passwords: ""
          existingSecret: portfolio-kafka-credentials
        controller:
          replicaCount: 1
          persistence:
            enabled: true
            size: 8Gi
        broker:
          replicaCount: 1
          persistence:
            enabled: true
            size: 8Gi
        service:
          type: NodePort
          nodePorts:
            client: "30092"
            external: "30093"
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
