apiVersion: v1
kind: Secret
metadata:
  name: portfolio-mongodb-credentials
  namespace: portfolio-db
type: Opaque
stringData:
  mongodb-root-password: YOUR_ROOT_PASSWORD
  mongodb-passwords: YOUR_APP_PASSWORD
