apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 18.1.10
    helm:
      releaseName: portfolio-mongodb
      values: |
        image:
          registry: registry-1.docker.io
          repository: bitnami/mongodb
          tag: latest
        auth:
          rootUser: root
          usernames:
            - kyhan
          databases:
            - portfolio_content
          existingSecret: portfolio-mongodb-credentials
        persistence:
          enabled: true
          size: 20Gi
        service:
          type: NodePort
          nodePorts:
            mongodb: 30017
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

