apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.4.5
    helm:
      releaseName: portfolio-postgres
      values: |
        global:
          postgresql:
            auth:
              username: app_user
              password: app_password
              database: portfolio_db
        primary:
          persistence:
            enabled: true
            size: 20Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

