apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 24.0.0
    helm:
      releaseName: portfolio-redis
      values: |
        image:
          registry: registry-1.docker.io
          repository: bitnami/redis
          tag: latest
        auth:
          existingSecret: portfolio-redis-credentials
          existingSecretPasswordKey: redis-password
        master:
          persistence:
            enabled: true
            size: 8Gi
          service:
            type: NodePort
            nodePorts:
              redis: "30379"
        replica:
          replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
